# Copyright (c) Tampere University 2020.
# This software has been developed in ProCemPlus-project funded by Business Finland.
# This code is licensed under the MIT license.
# See the LICENSE.txt in the project root for the license terms.
#
# Main author(s): Ville Heikkila

FROM python:3.6.9-slim
WORKDIR /data
COPY dashboard_html.py .
CMD ["python", "-u", "-m", "dashboard_html"]
